name: gauge_indicator
description: An animated, highly customizable, open source, Flutter gauge widget.
version: 0.4.3
homepage: https://github.com/gonuit/gauge_indicator

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ^2.2.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.6
  collection: ^1.15.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

funding:
  - https://www.paypal.com/donate/?hosted_button_id=Z82R98MAR4URE
  - https://www.buymeacoffee.com/kamilklyta

topics:
  - widgets
  - animation
  - gauge
  - gauge-indicator
  - gauges

screenshots:
  - description: The gauge_indicator package thumbnail.
    path: thumbnail.png
